#!/bin/bash
cd /home/jovyan/

NOTEBOOK_IN="github_dashboard_cofinanciamento_ms2025-06-12.ipynb"
NOTEBOOK_OUT="github_dashboard_cofinanciamento_ms2025-06-12_EXECUTED.ipynb"

jupyter nbconvert --to notebook --execute "${NOTEBOOK_IN}" --output "${NOTEBOOK_OUT}" --allow-errors --debug
